config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  def index
    @tasks = Task.all
  end

  def show
  
  end

  
  def new
    @task = Task.new
  end

  
  def edit
  end

  
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "タスクは保存されました。" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
   
    def set_task
      @task = Task.find(params[:id])
    end

    
    def task_params
      params.require(:task).permit(:tite, :start_at, :end_at, :is_all_day, :introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <h1>Ruby on Rails スケジュール管理アプリ</h1>
  </header>

    <%= yield %>

    <footer>
    <h1>
    現在日時:<%= Date.current.strftime('%Y/%m/%d') %>
    スケジュールの合計: <%= @tasks.length if @tasks.present? %>
    </h1>
  </footer>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :"タイトル", style: "display: block" %>
    <%= form.text_field :tite %>
  </div>

  <div>
    <%= form.label :"開始日", style: "display: block" %>
    <%= form.date_field :start_at %>
  </div>

  <div>
    <%= form.label :"終了日", style: "display: block" %>
    <%= form.date_field :end_at %>
  </div>

  <div>
    <%= form.label :"終日", style: "display: block" %>
    <p>終日の場合はチェックを入れます</p>
    <%= form.check_box :is_all_day %>
  </div>
  
  <div>
    <%= form.label :"スケジュールメモ", style: "display: block" %>
    <%= form.text_area :introduction %>
  </div>

  <div>
    <%= form.submit "登録完了する" %>
  </div>
<% end %>

<style>
input[type="checkbox"] { width: auto; }


</style>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>id:</strong>
    <%= task.id %>
  </p>

  <p>
    <strong>タイトル:</strong>
    <%= task.tite %>
  </p>

  <p>
    <strong>開始日:</strong>
    <%= task.start_at&.strftime('%Y年%m月%d日 %H時%M分') %>
  </p>

  <p>
    <strong>終了日:</strong>
    <%= task.end_at&.strftime('%Y年%m月%d日 %H時%M分') %>
  </p>

  <p>
    <strong>終日:</strong>
    <%= task.is_all_day ? 'O' : 'X' %>
  </p>

  <p>
    <strong>スケジュール更新日:</strong>
    <%= task.created_at&.strftime('%Y年%m月%d日 %H時%M分') %>
  </p>

</div>

app/views/tasks/call.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>


button{
        background-color: transparent;
        border: none;
        cursor: pointer;
        outline: none;
        padding: 0;
        appearance: none;
}















new/viw
<h1>スケジュールの新規作成</h1>

<%= render "form", task: @task %>

a:-webkit-any-link {
    color: -webkit-link;
    text-decoration: underline;
    cursor: auto;
}
a:-webkit-any-link:active {
    color: -webkit-activelink
}
/* HTML5 ruby elements */
ruby, rt {
    text-indent: 0; /* blocks used for ruby rendering should not trigger this */
}
rt {
    line-height: normal;
    -webkit-text-emphasis: none;
}
ruby > rt {
    display: block;
    font-size: 50%;
    text-align: start;
}

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  
  <%= link_to "スケジュール一覧に戻る", tasks_path %>
</div>

app/views/tasks/index.html.erb
<body>
  <div class="main_container">
    <div class="information">
    <h2>スケジュール一覧</h2>

</div>
    <table>
    <thead>
        <tr>
            <th>ID</th>
            <th>タイトル</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>終日</th>
            <th>スケジュール更新日時</th>
            <th>確認</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>

    <tbody>
<% @tasks.each do |task| %>
                <tr>
                    <td><%= task.id %></td>
                    <td><%= task.tite %></td>
                    <td><%= task.start_at&.strftime('%Y年%m月%d日 %H時%M分') %></td>
                    <td><%= task.end_at&.strftime('%Y年%m月%d日 %H時%M分') %></td>
                    <td><%= task.is_all_day ? 'O' : 'X' %></td>
                    <td><%= task.created_at&.strftime('%Y年%m月%d日 %H時%M分') %></td>
                    <td>
                       <%= link_to "確認", task %>
                    </td>
                    <td>
                        
                        <%= link_to "編集", edit_task_path(task) %>
                    </td>
                    <td>
                    <div>
                        <%= button_to "このタスクを削除する",task_path(task) , method: :delete, class: "clear" %>
                    </div>
                    </td>
                </tr>
                
                </div>
<% end %>
    </tbody>
</table>

<%= link_to "新規作成", new_task_path %>
</body>

app/views/tasks/new.html.erb
<h1>スケジュールの新規作成</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/show.html.erb
<p>
    <strong>id:</strong>
    <%= @task.id %>
  </p>

  <p class="any">
    <strong>タイトル:</strong>
    <%= @task.tite %>
  </p>

  <p>
    <strong>開始日:</strong>
    <%= @task.start_at %>
  </p>

  <p>
    <strong>投稿日時:</strong>
    <%= @task.end_at %>
  </p>

  <p>
    <strong>終日:</strong>
    <%= @task.is_all_day %>
  </p>

  <p>
    <strong>スケジュールメモ:</strong>
    <%= @task.introduction %>
  </p>



<div>
  <%= link_to "このタスクを編集する", edit_task_path(@task) %> |
  <%= link_to "一覧に戻る", tasks_path %>

  <%= button_to "このタスクを削除する", @task, method: :delete %>

  </div>